apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lura00/gitops.git
    targetRevision: main
    path: elasticsearch/vendor/elasticsearch-8.5.1   # match ELASTICSEARCH_CHART_VERSION
    helm:
      valueFiles:
        - ../../values/base.yaml
        - ../../values/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
