apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lura00/gitops.git
    # chart: jenkins
    targetRevision: main
    path: jenkins/Chart.yaml
    helm:
      valueFiles:
        - jenkins/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
