apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-luigi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lura00/gitops.git
    targetRevision: main
    path: jenkins/jenkins             # <-- FIXED
    helm:
      valueFiles:
        - values.yaml          # <-- FIXED
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

