apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lura00/gitops.git
    targetRevision: main
    # match this to your vendored folder:
    # kube-state-metrics/vendor/kube-state-metrics-6.3.0  or  kube-state-metrics/vendor/kube-state-metrics-6.4.0
    path: kube-state-metrics/vendor/kube-state-metrics-6.3.0
    helm:
      valueFiles:
        - ../../values/base.yaml
        - ../../values/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-state-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
