apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lura00/gitops.git
    targetRevision: main
    path: local-path-provisioner/vendor/local-path-provisioner-0.0.33
    helm:
      valueFiles:
        - ../../values/base.yaml
        - ../../values/custom-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
